trigger-hello-world:
	act workflow_dispatch -P ubuntu-24.04=node:16-bullseye-slim -W '../../.github/workflows/01-hello-world.yaml'

trigger-workflows-jobs-steps:
	act workflow_dispatch -P ubuntu-24.04=node:16-bullseye-slim -W '../../.github/workflows/02-workflows-jobs-steps.yaml'
